### ISSUE TITLE
How to remove or rebuild a version?

### ISSUE THREAD

**Issue by ArthurClemens** [erln8/erln8#16]
On Mac OS X the default config does not contain `--with-ssl`. Now I have added this, I want to rebuild the erlang version. Using `--build` generates the message

```
A version of Erlang already exists with the id OTP-18.0.3
```

**Comment by bookshelfdave** [comment]
This is a feature that I'd like to add, but in the meantime:

1) Remove the entry in `~/.erln8/config` under the `[Erlangs]` section
2) remove the directory from `~/.erln8.d/otps/<someversion>`
