### ISSUE TITLE
install.sh looks wrong

### ISSUE THREAD

**Issue by josephDunne** [erln8/erln8#9]
the install.sh script that comes with the prebuilt packages listed on the install page seems wrong (at least in the OS X package:

``` bash
cp erln8 ~/.erln8.d/bin/erln8
cp erln8 ~/.erln8.d/bin/reo
cp erln8 ~/.erln8.d/bin/reo3
```

should it be:

``` bash
cp erln8 ~/.erln8.d/bin/erln8
cp reo ~/.erln8.d/bin/reo
cp reo3 ~/.erln8.d/bin/reo3
```

**Comment by bookshelfdave** [comment]
It looks wrong... but it's actually fine. All programs use the same binary, and [check argv[0]](https://github.com/erln8/erln8/blob/master/src/app.d#L104) when starting up. I could change the install file, and it would work the same. I suppose I should.

**Comment by josephDunne** [comment]
cool was just checking thanks
